# Generated by Django 5.2.3 on 2025-07-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='goal_amount',
            new_name='target_amount',
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
